### ISSUE TITLE
Missing MacOS package in conda-forge

### ISSUE THREAD

**Issue by napetrov** [AnacondaRecipes/intel_repack-feedstock#10]
Hi,
there is no MacOS DAAL packages in conda-forge channel. Are they generated as part of this recipe or some another process?

https://anaconda.org/conda-forge/daal-devel/files

**Comment by napetrov** [comment]
@msarahan @soapy1  @mingwandroid  @jjhelmus  - could you please help with this issue?

**Comment by mingwandroid** [comment]
I will not have any time to add this to conda-forge, sorry. It is a community effort so feel free to help out.

This is not the issue tracker for conda-forge so I am closing it.

I recommend you open an issue at https://github.com/conda-forge/intel_repack-feedstock.

**Comment by napetrov** [comment]
ok, thanks! 
@mingwandroid  - what is then relation of this repo to one in conda-forge?

**Comment by msarahan** [comment]
Most recipes have their "canonical" version at conda-forge. Anaconda worked to make conda-forge the upstream source of recipes to facilitate easier community contribution. There are a few exceptions where Anaconda maintains recipes that conda-forge does not want for various reasons - license concerns, build time, etc. This recipe is one of those. Anaconda maintains this recipe because they have a close relationship with Intel. The conda-forge community has historically chosen to not take up this recipe because it is a repackage, not a build from source.
